# Generated by Django 3.2.7 on 2021-09-20 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='image',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='HashTag',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
